CREATE USER IF NOT EXISTS 'cqa'@'%' IDENTIFIED BY 'cqa_secure_pass_2024';
CREATE DATABASE IF NOT EXISTS cqa CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON cqa.* TO 'cqa'@'%';
FLUSH PRIVILEGES;
